# Generated by Django 5.1 on 2024-08-10 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=64, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('senha', models.CharField(max_length=64, verbose_name='Senha')),
                ('idade', models.IntegerField(blank=True, null=True, verbose_name='Idade')),
            ],
        ),
    ]
