version: "4.33.0"
services:
  database:
    container_name: login
    image: postgres:16.3
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
